MandarinMedien\MMMediaBundle\Entity\Media:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: true
        description:
            type: string
            length: 255
            nullable: true
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        copyright:
            type: string
            length: 150
            nullable: true
        author:
            type: string
            length: 100
            nullable: true
        mediaType:
            type: string
            length: 100
        mediaTypeReference:
            type: string
            length: 150
        mediaTypeMetadata:
            type: json_array
            nullable: true


    lifecycleCallbacks:
        prePersist: [ prePersist ]
        preUpdate: [ preUpdate ]
