MandarinMedien\MMMediaBundle\Entity\MediaSortable:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        position:
            type: integer
    manyToOne:
        media:
            targetEntity: MandarinMedien\MMMediaBundle\Entity\Media
            cascade:
                - persist
    lifecycleCallbacks: {}
