mm_media:
    media_types:
        types:
            - MandarinMedien\MMMediaBundle\MediaType\ImageMediaType
            - MandarinMedien\MMMediaBundle\MediaType\FileMediaType
            - MandarinMedien\MMMediaBundle\MediaType\VideoMediaType
            - MandarinMedien\MMMediaBundle\MediaType\YoutubeMediaType
            - MandarinMedien\MMMediaBundle\MediaType\VimeoMediaType

assetic:
    assets:
        mmmedia_assets_js:
            inputs:
                - '@MMMediaBundle/Resources/public/js/dropzone.4.2.0.min.js'
                - '@MMMediaBundle/Resources/public/js/dragula.3.5.4.min.js'
                - '@MMMediaBundle/Resources/public/js/MMMediaBundle.js'
        mmmedia_assets_css:
            inputs:
                - '@MMMediaBundle/Resources/public/css/dragula.3.5.4.min.css'
                - '@MMMediaBundle/Resources/public/css/dropzone.4.2.0.min.css'
                - '@MMMediaBundle/Resources/public/css/MMMediaBundle.css'


# Twig Configuration
twig:
    form:
        resources:
            - MMMediaBundle:Form:mmmedia_upload_collection_widget.html.twig
            - MMMediaBundle:Form:mmmedia_upload_widget.html.twig