mm_media:
    media_types:
        types:
            - MandarinMedien\MMMediaBundle\MediaType\ImageMediaType
            - MandarinMedien\MMMediaBundle\MediaType\FileMediaType
            - MandarinMedien\MMMediaBundle\MediaType\VideoMediaType
            - MandarinMedien\MMMediaBundle\MediaType\YoutubeMediaType
            - MandarinMedien\MMMediaBundle\MediaType\VimeoMediaType