mm_media:
    media_types:
        types:
            - 'MandarinMedien\MMMediaBundle\MediaType\ImageMediaType'
            - 'MandarinMedien\MMMediaBundle\MediaType\FileMediaType'
            #- 'MandarinMedien\MMMediaBundle\MediaType\VideoMediaType'
            - 'MandarinMedien\MMMediaBundle\MediaType\YoutubeMediaType'
            #- 'MandarinMedien\MMMediaBundle\MediaType\VimeoMediaType'

# Twig Configuration
twig:
    form_themes:
        - 'MMMediaBundle:Form:mmmedia_upload_collection_widget.html.twig'
        - 'MMMediaBundle:Form:mmmedia_upload_widget.html.twig'